version: "3"

services:
  base:
    container_name: coriander
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev:/dev
      - $CORIANDER_HOME/build:/coriander/build/out:rw
    
  amd:
    extends: base
    build:
      target: AMD
  beignet:
    container_name: coriander
    build: 
      target: beignet
  nvidia-1404:
    container_name: coriander
    build: 
      target: nvidia-1404
