FROM ubuntu:16.04

ARG GIT_BRANCH=master

RUN apt-get update

RUN apt-get install -y beignet-opencl-icd clinfo

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake cmake-curses-gui git llvm-3.8-dev clang-3.8 gcc g++ libc6-dev zlib1g-dev \
    curl ca-certificates build-essential

RUN git clone --recursive https://github.com/hughperkins/cuda-on-cl -b ${GIT_BRANCH}

# lets add python3 virtualenv, so can run the python tests too
# this is not strictly necessary for using/running cuda-on-cl
# in fact, it's not necessary at all :-P
RUN apt-get install -y --no-install-recommends python3 python3-dev python-virtualenv

RUN virtualenv -p python3 /env3

RUN . /env3/bin/activate && \
    pip install -r /cuda-on-cl/test/requirements.txt

RUN cd cuda-on-cl && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTS=ON && \
    make -j 8

RUN cd cuda-on-cl && \
    cd build && \
    make install
