FROM nvidia/cuda:8.0-cudnn5-devel

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake cmake-curses-gui git llvm-3.8-dev clang-3.8 gcc g++ libc6-dev \
    nvidia-opencl-icd-361 clinfo

# RUN nvidia-smi

# RUN clinfo

RUN git clone --recursive https://github.com/hughperkins/cuda-on-cl

RUN cd cuda-on-cl && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j 8

RUN cd cuda-on-cl && \
    cd build && \
    make install


