FROM ubuntu:16.04

ARG GIT_BRANCH=master

RUN apt-get update

RUN apt-get install -y beignet-opencl-icd clinfo

RUN apt-get install -y --no-install-recommends \
    cmake cmake-curses-gui git llvm-3.8-dev clang-3.8 gcc g++ libc6-dev zlib1g-dev \
    curl ca-certificates build-essential

RUN git clone --recursive https://github.com/hughperkins/Coriander -b ${GIT_BRANCH}

RUN cd Coriander && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTS=ON && \
    make -j 8

RUN cd Coriander && \
    cd build && \
    make install
